import { NextRequest, NextResponse } from "next/server";
import fs from "fs/promises";
import path from "path";

function getServerDir(serverId: string): string {
  return path.join(process.cwd(), ".data", "servers", serverId);
}

function parseProperties(content: string): Record<string, string> {
  const result: Record<string, string> = {};
  const lines = content.split(/\r?\n/);
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#") || trimmed.startsWith("!")) continue;
    const eqIdx = trimmed.indexOf("=");
    if (eqIdx !== -1) {
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      result[key] = val;
    }
  }
  return result;
}

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const propPath = path.join(getServerDir(id), "server.properties");

    let raw = "";
    try {
      raw = await fs.readFile(propPath, "utf8");
    } catch {
      raw = "# Minecraft server properties\n# Generated by Rubber Panel\nmotd=A Minecraft Server powered by Rubber Panel\ngamemode=survival\ndifficulty=easy\npvp=true\nhardcore=false\nmax-players=20\nonline-mode=true\nview-distance=10\nsimulation-distance=8\nallow-flight=false\nwhite-list=false\nenable-command-block=false\nspawn-animals=true\nspawn-monsters=true\nspawn-npcs=true\ngenerate-structures=true\nlevel-name=world\n";
    }

    const parsed = parseProperties(raw);

    return NextResponse.json({
      properties: parsed,
      raw,
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message || "Failed to read server.properties" }, { status: 500 });
  }
}

export async function PUT(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const body = await req.json();
    const { properties, raw } = body;

    const propPath = path.join(getServerDir(id), "server.properties");

    let contentToWrite = "";

    if (typeof raw === "string") {
      contentToWrite = raw;
    } else if (properties && typeof properties === "object") {
      // Rebuild properties file cleanly
      const lines = [
        "# Minecraft server properties",
        `# Modified via Rubber Panel on ${new Date().toISOString()}`,
      ];

      for (const [key, value] of Object.entries(properties)) {
        lines.push(`${key}=${value}`);
      }

      contentToWrite = lines.join("\n") + "\n";
    } else {
      return NextResponse.json({ error: "Invalid properties or raw payload" }, { status: 400 });
    }

    await fs.writeFile(propPath, contentToWrite, "utf8");

    return NextResponse.json({
      success: true,
      properties: parseProperties(contentToWrite),
      raw: contentToWrite,
    });
  } catch (err: any) {
    return NextResponse.json({ error: err.message || "Failed to update server.properties" }, { status: 500 });
  }
}
